sudo: false
language: java

cache:
  directories:
    - $HOME/.m2

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  
matrix:
  include:
    # GraalVM
    - env: JDK='GraalVM 20'
      install: . ./install-jdk.sh --url "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz"

script:
  - gu install native-image
  - cd projetos/graal
  - mvn package -P native
  
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH"
  file: "target/cid-aws-1.0.0-SNAPSHOT-runner"
  skip_cleanup: true
  on:
    tags: true
